### PR TITLE
Add Code Of Conduct

### PR DESCRIPTION
**Pull request by ivannieto**

### CODE REVIEW

**Comment by jcrugzz** [comment]
@ivannieto Thanks for adding this!

**Comment by jcrugzz** [comment]
@ivannieto i realized i merged to fast, would you mind adding a link to this in the README?

**Comment by ivannieto** [comment]
@jcrugzz do you want to say adding the link to this file in the repo? or to the default Covenant?

**Comment by jcrugzz** [comment]
@ivannieto add a link to the code of conduct file in this repo to our README so people have a direct link.

**Comment by ivannieto** [comment]
Done in https://github.com/nodejitsu/node-http-proxy/pull/1120

**Pull request merged**
