### PR TITLE
Improved formatting for some lines in README.md

### PR DESCRIPTION
**Pull request by ivannieto**
Corresponding to the explanations preceded by the '†' symbol. I had to re-read those lines when reading the doc, I think makes more reading-sense now.

Please review. Does not change the README itself.

### CODE REVIEW

**Comment by ivannieto** [comment]
:thinking: why is it showing conflicts?

**Comment by jcrugzz** [comment]
@ivannieto can you rebase your changes off `origin/master`? you are still based on your previous git tree before your changes were merged. That is why there are so many extra commits above

**Comment by ivannieto** [comment]
sure @jcrugzz my bad!

**Comment by ivannieto** [comment]
Closing and reopening a new PR.

**Pull request closed without merging**
