### PR TITLE
Updated Version of follow-redirects from 1.0.0 to 1.14.8

### PR DESCRIPTION
**Pull request by Annniee1**
We are facing bugs in older version .Please Upgrade the version

### CODE REVIEW

**Comment by Annniee1** [comment]
@peters @darashi @benatkin @indexzero Please Review this Pull Request

**Comment by Annniee1** [comment]
Hi @peters @darashi @benatkin @indexzero @Jimbly. Any Plan to merge this Pull Request?

**Comment by Jimbly** [comment]
I'm not a maintainer of this repo (as far as I know, it's dead), however I published [http-proxy-node16](https://www.npmjs.com/package/http-proxy-node16) a while back, which is a fork of this repo that works on Node 16 without gigantic memory leaks (#1559).  Feel free to send a PR [over there](https://github.com/Jimbly/node-http-proxy) and I'll publish it to NPM.

**Comment by Jimbly** [comment]
That being said, I believe `follow-redirects v1.14.8` matches the semver specified here already, so I'm not sure this change is needed - if you install v1.14.8, it should use it, I think?

**Comment by Annniee1** [comment]
> That being said, I believe `follow-redirects v1.14.8` matches the semver specified here already, so I'm not sure this change is needed - if you install v1.14.8, it should use it, I think?

Yaa @Jimbly . It matches the semver version specified. I am not sure why previously i was getting 1.14.7 and not 1.14.8.
But yes, it is working now.
Thanks!

**Pull request closed without merging**
