### PR TITLE
Add followRedirects option

### PR DESCRIPTION
**Pull request by n30n0v**
Add  `followRedirect` option which specify whether you want to follow redirects. (true/false, Default: false)

### CODE REVIEW

**Comment by apsavin** [comment]
Should we support 0.10 and 0.12?
I think, no (https://github.com/nodejs/LTS).

**Comment by n30n0v** [comment]
@jcrugzz Can you please take a look? What do you think?

**Comment by trickpattyFH20** [comment]
would love to see this merged!

**Comment by mohamedmansour** [comment]
This works great! I just tried it and it working

**Comment by jcrugzz** [comment]
Thanks @n30n0v! This package seems small enough that I think its a good feature add. I will cherry-pick your commit into my `maintenance` branch that I plan to merge later tonight.

**Comment by jcrugzz** [comment]
superceded by #1251

**Pull request closed without merging**
