### PR TITLE
Made it not to crash with omited Host http header

### PR DESCRIPTION
**Pull request by alexindigo**
When tools like HAProxy run health checks they don't supply http Host header,
which makes http-proxy to crash, pretty unfortunate side-effect for a health check. :)

### CODE REVIEW

**Comment by jcrugzz** [comment]
Thanks!

**Comment by alexindigo** [comment]
Thank you. Can you publish it on npm as well? :)

**Comment by jcrugzz** [comment]
Done. new version at `1.15.0`

**Comment by alexindigo** [comment]
Thanks a lot.

**Pull request merged**
